name: Test Application

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - "*"
    types: [opened, synchronize]


jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel all builds
        uses: styfle/cancel-workflow-action@0.9.1
  
  test_client:
    needs: [avoid_reduncy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Intalling Dependencies of Project
        run: |
          cd client
          npm install --no-audit --no-fund --no-optional
      - name: Eslint
        run: | 
          cd client
          npm run lint
      - name: Testing with Jest
        run: | 
          cd client
          npm run test

  test_server:
    needs: [avoid_reduncy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Intalling Dependencies of Project
        run: |
          cd server
          npm install --no-audit --no-fund --no-optional
      - name: Testing with Jest
        run: | 
          cd server
          npm run test